//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amellar.Modules.HealthPermit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amellar.Modules.HealthPermit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Annual_Inspection_letter_01 {
            get {
                object obj = ResourceManager.GetObject("Annual_Inspection_letter_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Annual_Inspection_letter_v2_01 {
            get {
                object obj = ResourceManager.GetObject("Annual_Inspection_letter_v2_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BALANTACAN_LOGO {
            get {
                object obj = ResourceManager.GetObject("BALANTACAN_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BANGCAL_PUGAD_LOGO {
            get {
                object obj = ResourceManager.GetObject("BANGCAL_PUGAD_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BANGCAL_SINUBLI_LOGO {
            get {
                object obj = ResourceManager.GetObject("BANGCAL_SINUBLI_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue {
            get {
                object obj = ResourceManager.GetObject("blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CALANGAIN {
            get {
                object obj = ResourceManager.GetObject("CALANGAIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CONCEPCION {
            get {
                object obj = ResourceManager.GetObject("CONCEPCION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DEL_CARMEN {
            get {
                object obj = ResourceManager.GetObject("DEL_CARMEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELA_PAZ {
            get {
                object obj = ResourceManager.GetObject("DELA_PAZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DON_IGNACIO_DIMSON {
            get {
                object obj = ResourceManager.GetObject("DON_IGNACIO_DIMSON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eBALANTACAN {
            get {
                object obj = ResourceManager.GetObject("eBALANTACAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eBANCAL_PUGAD {
            get {
                object obj = ResourceManager.GetObject("eBANCAL_PUGAD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eBANCAL_SINUBALI {
            get {
                object obj = ResourceManager.GetObject("eBANCAL_SINUBALI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eCALANGAIN {
            get {
                object obj = ResourceManager.GetObject("eCALANGAIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eCONCEPCION {
            get {
                object obj = ResourceManager.GetObject("eCONCEPCION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eDEL_CARMEN {
            get {
                object obj = ResourceManager.GetObject("eDEL_CARMEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eDELA_PAZ {
            get {
                object obj = ResourceManager.GetObject("eDELA_PAZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eDON_IGNACIO_DIMSON_DAU_2 {
            get {
                object obj = ResourceManager.GetObject("eDON_IGNACIO_DIMSON_DAU_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eLOURDES {
            get {
                object obj = ResourceManager.GetObject("eLOURDES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ePRADO_SIONGCO {
            get {
                object obj = ResourceManager.GetObject("ePRADO_SIONGCO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eREMEDIOS {
            get {
                object obj = ResourceManager.GetObject("eREMEDIOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_AGUSTIN {
            get {
                object obj = ResourceManager.GetObject("eSAN_AGUSTIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_ANTONIO {
            get {
                object obj = ResourceManager.GetObject("eSAN_ANTONIO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_FRANCISCO {
            get {
                object obj = ResourceManager.GetObject("eSAN_FRANCISCO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_JOSE_APUNAN {
            get {
                object obj = ResourceManager.GetObject("eSAN_JOSE_APUNAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_JOSE_GUMI {
            get {
                object obj = ResourceManager.GetObject("eSAN_JOSE_GUMI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_JUAN {
            get {
                object obj = ResourceManager.GetObject("eSAN_JUAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_MATIAS {
            get {
                object obj = ResourceManager.GetObject("eSAN_MATIAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_MIGUEL {
            get {
                object obj = ResourceManager.GetObject("eSAN_MIGUEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_NICOLAS1 {
            get {
                object obj = ResourceManager.GetObject("eSAN_NICOLAS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_NICOLAS2 {
            get {
                object obj = ResourceManager.GetObject("eSAN_NICOLAS2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_PABLO1 {
            get {
                object obj = ResourceManager.GetObject("eSAN_PABLO1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_PABLO2 {
            get {
                object obj = ResourceManager.GetObject("eSAN_PABLO2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_PEDRO_SAUG {
            get {
                object obj = ResourceManager.GetObject("eSAN_PEDRO_SAUG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_PERDO_PALCARANGAN {
            get {
                object obj = ResourceManager.GetObject("eSAN_PERDO_PALCARANGAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_RAFAEL_BARUYA {
            get {
                object obj = ResourceManager.GetObject("eSAN_RAFAEL_BARUYA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_ROQUE_ARBOL {
            get {
                object obj = ResourceManager.GetObject("eSAN_ROQUE_ARBOL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_ROQUE_DAU {
            get {
                object obj = ResourceManager.GetObject("eSAN_ROQUE_DAU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_SAN_ISIDRO {
            get {
                object obj = ResourceManager.GetObject("eSAN_SAN_ISIDRO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSAN_VICENTE {
            get {
                object obj = ResourceManager.GetObject("eSAN_VICENTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSANTIAGO {
            get {
                object obj = ResourceManager.GetObject("eSANTIAGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_BARBARA {
            get {
                object obj = ResourceManager.GetObject("eSTA_BARBARA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_CATALINA {
            get {
                object obj = ResourceManager.GetObject("eSTA_CATALINA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_CRUZ {
            get {
                object obj = ResourceManager.GetObject("eSTA_CRUZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_LUCIA {
            get {
                object obj = ResourceManager.GetObject("eSTA_LUCIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_MARIA {
            get {
                object obj = ResourceManager.GetObject("eSTA_MARIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_MONICA {
            get {
                object obj = ResourceManager.GetObject("eSTA_MONICA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_RITA {
            get {
                object obj = ResourceManager.GetObject("eSTA_RITA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_TERESA_01 {
            get {
                object obj = ResourceManager.GetObject("eSTA_TERESA_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTA_TERESA_02 {
            get {
                object obj = ResourceManager.GetObject("eSTA_TERESA_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTO_CRISTO {
            get {
                object obj = ResourceManager.GetObject("eSTO_CRISTO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTO_DOMINGO {
            get {
                object obj = ResourceManager.GetObject("eSTO_DOMINGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTO_NINO {
            get {
                object obj = ResourceManager.GetObject("eSTO_NINO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eSTO_TOMAS {
            get {
                object obj = ResourceManager.GetObject("eSTO_TOMAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lineBOTTOM {
            get {
                object obj = ResourceManager.GetObject("lineBOTTOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lineDIAGONAL1 {
            get {
                object obj = ResourceManager.GetObject("lineDIAGONAL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lineTOP {
            get {
                object obj = ResourceManager.GetObject("lineTOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOURDES {
            get {
                object obj = ResourceManager.GetObject("LOURDES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lubaologo {
            get {
                object obj = ResourceManager.GetObject("Lubaologo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PRADO_SIONGCO {
            get {
                object obj = ResourceManager.GetObject("PRADO_SIONGCO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap REMEDIOS {
            get {
                object obj = ResourceManager.GetObject("REMEDIOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_AGUSTIN {
            get {
                object obj = ResourceManager.GetObject("SAN_AGUSTIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_ANTONIO {
            get {
                object obj = ResourceManager.GetObject("SAN_ANTONIO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap san_francisco_new_logo {
            get {
                object obj = ResourceManager.GetObject("san_francisco_new_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_ISIDRO_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_ISIDRO_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_JOSE_APUNAN {
            get {
                object obj = ResourceManager.GetObject("SAN_JOSE_APUNAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap san_jose_gumi_logo {
            get {
                object obj = ResourceManager.GetObject("san_jose_gumi_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_JUAN_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_JUAN_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap san_matias_LOGO {
            get {
                object obj = ResourceManager.GetObject("san_matias_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_MIGUEL_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_MIGUEL_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_NICOLAS1_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_NICOLAS1_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_NICOLAS2_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_NICOLAS2_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_PABLO_1_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_PABLO_1_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_PABLO_2_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_PABLO_2_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_PEDRO_PALCARANGAN_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_PEDRO_PALCARANGAN_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_PEDRO_SAUG {
            get {
                object obj = ResourceManager.GetObject("SAN_PEDRO_SAUG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_RAFAEL_BARUYA_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_RAFAEL_BARUYA_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_ROQUE_ARBOL {
            get {
                object obj = ResourceManager.GetObject("SAN_ROQUE_ARBOL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_ROQUE_DAU_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_ROQUE_DAU_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAN_VICENTE_LOGO {
            get {
                object obj = ResourceManager.GetObject("SAN_VICENTE_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SANITARY_PERMIT_letter_01 {
            get {
                object obj = ResourceManager.GetObject("SANITARY_PERMIT_letter_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SANITARY_PERMIT_letter_v3 {
            get {
                object obj = ResourceManager.GetObject("SANITARY_PERMIT_letter_v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SANTIAGO_LOGO {
            get {
                object obj = ResourceManager.GetObject("SANTIAGO_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_BARBARA_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_BARBARA_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_CATALINA_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_CATALINA_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_CRUZ_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_CRUZ_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_LUCIA_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_LUCIA_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_MARIA_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_MARIA_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_MONICA_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_MONICA_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_RITA_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_RITA_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_TERESA_1ST_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_TERESA_1ST_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STA_TEREZA_2_LOGO {
            get {
                object obj = ResourceManager.GetObject("STA_TEREZA_2_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STO_CRISTO_LOGO {
            get {
                object obj = ResourceManager.GetObject("STO_CRISTO_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STO_DOMINGO_LOGO {
            get {
                object obj = ResourceManager.GetObject("STO_DOMINGO_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STO_NINO {
            get {
                object obj = ResourceManager.GetObject("STO_NINO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STO_TOMAS_LOGO {
            get {
                object obj = ResourceManager.GetObject("STO_TOMAS_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled_1 {
            get {
                object obj = ResourceManager.GetObject("Untitled_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
