//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTAS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTAS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _abstract {
            get {
                object obj = ResourceManager.GetObject("abstract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ABiling {
            get {
                object obj = ResourceManager.GetObject("ABiling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_cancelled_OR {
            get {
                object obj = ResourceManager.GetObject("abstract-cancelled-OR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_cencelledor {
            get {
                object obj = ResourceManager.GetObject("abstract-cencelledor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_check {
            get {
                object obj = ResourceManager.GetObject("abstract-check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_checks {
            get {
                object obj = ResourceManager.GetObject("abstract-checks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_collection {
            get {
                object obj = ResourceManager.GetObject("abstract-collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_collection1 {
            get {
                object obj = ResourceManager.GetObject("abstract-collection1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_CreditMemo {
            get {
                object obj = ResourceManager.GetObject("abstract-CreditMemo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_CreditMemos_ExcessCheck {
            get {
                object obj = ResourceManager.GetObject("abstract-CreditMemos_ExcessCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_CreditMemos_ExcessTax {
            get {
                object obj = ResourceManager.GetObject("abstract-CreditMemos_ExcessTax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_debitMemo {
            get {
                object obj = ResourceManager.GetObject("abstract-debitMemo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_posted_OR {
            get {
                object obj = ResourceManager.GetObject("abstract-posted-OR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abstract_postedor {
            get {
                object obj = ResourceManager.GetObject("abstract-postedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ace_abstract_collection {
            get {
                object obj = ResourceManager.GetObject("ace-abstract-collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap app_bg_bpls_2 {
            get {
                object obj = ResourceManager.GetObject("app-bg-bpls-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap app_bg_business {
            get {
                object obj = ResourceManager.GetObject("app-bg-business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background_bta2 {
            get {
                object obj = ResourceManager.GetObject("Background_bta2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Billing {
            get {
                object obj = ResourceManager.GetObject("Billing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Billing_cancel {
            get {
                object obj = ResourceManager.GetObject("Billing-cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap billing_cancelled {
            get {
                object obj = ResourceManager.GetObject("billing-cancelled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap billing_permit_update {
            get {
                object obj = ResourceManager.GetObject("billing-permit-update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blgf_reports {
            get {
                object obj = ResourceManager.GetObject("blgf-reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bpls_bta {
            get {
                object obj = ResourceManager.GetObject("bpls_bta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bpls_btas {
            get {
                object obj = ResourceManager.GetObject("bpls-btas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bpls_text_trans {
            get {
                object obj = ResourceManager.GetObject("bpls-text-trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bps_nav_exit {
            get {
                object obj = ResourceManager.GetObject("bps-nav_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bps_nav_logout {
            get {
                object obj = ResourceManager.GetObject("bps-nav_logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_unrenewed {
            get {
                object obj = ResourceManager.GetObject("business-unrenewed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusinessTax_Monitoring {
            get {
                object obj = ResourceManager.GetObject("BusinessTax-Monitoring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusinessTax_Monitoring_2 {
            get {
                object obj = ResourceManager.GetObject("BusinessTax-Monitoring_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_or {
            get {
                object obj = ResourceManager.GetObject("cancel-or", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap certificate {
            get {
                object obj = ResourceManager.GetObject("certificate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collection_list {
            get {
                object obj = ResourceManager.GetObject("collection-list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collection_summary {
            get {
                object obj = ResourceManager.GetObject("collection-summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap compromise_agreement {
            get {
                object obj = ResourceManager.GetObject("compromise-agreement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap compromise_agreement1 {
            get {
                object obj = ResourceManager.GetObject("compromise-agreement1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_query {
            get {
                object obj = ResourceManager.GetObject("data-query", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dc_ce_log {
            get {
                object obj = ResourceManager.GetObject("dc-ce_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debit_credit_reports {
            get {
                object obj = ResourceManager.GetObject("debit-credit-reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debit_credit_tagging {
            get {
                object obj = ResourceManager.GetObject("debit-credit-tagging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debitcredit_report {
            get {
                object obj = ResourceManager.GetObject("debitcredit-report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deficiency_record {
            get {
                object obj = ResourceManager.GetObject("deficiency-record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delinquency_report {
            get {
                object obj = ResourceManager.GetObject("delinquency-report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deliquency_list {
            get {
                object obj = ResourceManager.GetObject("deliquency-list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deliquency_summary {
            get {
                object obj = ResourceManager.GetObject("deliquency-summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DILG {
            get {
                object obj = ResourceManager.GetObject("DILG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dilg_report {
            get {
                object obj = ResourceManager.GetObject("dilg-report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gross_Monitoring {
            get {
                object obj = ResourceManager.GetObject("Gross-Monitoring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap liquidation_reports {
            get {
                object obj = ResourceManager.GetObject("liquidation-reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_cancelled_checks {
            get {
                object obj = ResourceManager.GetObject("list_cancelled-checks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notice_delinquency {
            get {
                object obj = ResourceManager.GetObject("notice-delinquency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notices {
            get {
                object obj = ResourceManager.GetObject("notices", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap or_declaration {
            get {
                object obj = ResourceManager.GetObject("or-declaration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap other_reports {
            get {
                object obj = ResourceManager.GetObject("other-reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap other_reports1 {
            get {
                object obj = ResourceManager.GetObject("other-reports1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pay_cancel {
            get {
                object obj = ResourceManager.GetObject("pay-cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pay_offline {
            get {
                object obj = ResourceManager.GetObject("pay-offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pay_online {
            get {
                object obj = ResourceManager.GetObject("pay-online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_debit_credit {
            get {
                object obj = ResourceManager.GetObject("payment_debit-credit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_history {
            get {
                object obj = ResourceManager.GetObject("payment-history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_history2 {
            get {
                object obj = ResourceManager.GetObject("payment_history2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_history21 {
            get {
                object obj = ResourceManager.GetObject("payment_history21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_protest {
            get {
                object obj = ResourceManager.GetObject("payment-protest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_records_add {
            get {
                object obj = ResourceManager.GetObject("payment-records_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_records_add1 {
            get {
                object obj = ResourceManager.GetObject("payment-records_add1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_records_delete {
            get {
                object obj = ResourceManager.GetObject("payment-records_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_records_delete1 {
            get {
                object obj = ResourceManager.GetObject("payment-records_delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_records_edit {
            get {
                object obj = ResourceManager.GetObject("payment-records_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_records_edit1 {
            get {
                object obj = ResourceManager.GetObject("payment-records_edit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap permit_update {
            get {
                object obj = ResourceManager.GetObject("permit_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap permit_update_1 {
            get {
                object obj = ResourceManager.GetObject("permit-update-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap posting_add {
            get {
                object obj = ResourceManager.GetObject("posting-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap posting_delete {
            get {
                object obj = ResourceManager.GetObject("posting-delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap posting_edit {
            get {
                object obj = ResourceManager.GetObject("posting-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RCD {
            get {
                object obj = ResourceManager.GetObject("RCD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RCD_reprint {
            get {
                object obj = ResourceManager.GetObject("RCD-reprint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_files {
            get {
                object obj = ResourceManager.GetObject("report-files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_manager {
            get {
                object obj = ResourceManager.GetObject("report-manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_manager1 {
            get {
                object obj = ResourceManager.GetObject("report-manager1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reprint_or {
            get {
                object obj = ResourceManager.GetObject("reprint-or", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reprint_rcd {
            get {
                object obj = ResourceManager.GetObject("reprint-rcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retire_billing {
            get {
                object obj = ResourceManager.GetObject("retire-billing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retirement_business {
            get {
                object obj = ResourceManager.GetObject("retirement-business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap revenue_examination {
            get {
                object obj = ResourceManager.GetObject("revenue-examination", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap soa_view {
            get {
                object obj = ResourceManager.GetObject("soa-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap summary_collection {
            get {
                object obj = ResourceManager.GetObject("summary-collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap summary_of_collection {
            get {
                object obj = ResourceManager.GetObject("summary-of-collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap task_manager {
            get {
                object obj = ResourceManager.GetObject("task-manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap teller_reportcollection {
            get {
                object obj = ResourceManager.GetObject("teller-reportcollection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap teller_transaction {
            get {
                object obj = ResourceManager.GetObject("teller-transaction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_setup {
            get {
                object obj = ResourceManager.GetObject("user-setup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap waive_surcharge_penalty {
            get {
                object obj = ResourceManager.GetObject("waive-surcharge-penalty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
