//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPLSBilling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPLSBilling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ABiling {
            get {
                object obj = ResourceManager.GetObject("ABiling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ABus {
            get {
                object obj = ResourceManager.GetObject("ABus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ace_inspector {
            get {
                object obj = ResourceManager.GetObject("ace-inspector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap app_bg_bpls_2 {
            get {
                object obj = ResourceManager.GetObject("app-bg-bpls-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap app_bg_business {
            get {
                object obj = ResourceManager.GetObject("app-bg-business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_add {
            get {
                object obj = ResourceManager.GetObject("application-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_cancel {
            get {
                object obj = ResourceManager.GetObject("application_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_edit {
            get {
                object obj = ResourceManager.GetObject("application-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_new_add {
            get {
                object obj = ResourceManager.GetObject("application_new-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_new_edit {
            get {
                object obj = ResourceManager.GetObject("application_new-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_new_edit1 {
            get {
                object obj = ResourceManager.GetObject("application_new-edit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_new_view {
            get {
                object obj = ResourceManager.GetObject("application_new-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_print_form {
            get {
                object obj = ResourceManager.GetObject("application-print-form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_reassesment {
            get {
                object obj = ResourceManager.GetObject("application-reassesment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_renewal_add {
            get {
                object obj = ResourceManager.GetObject("application_renewal-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_renewal_edit {
            get {
                object obj = ResourceManager.GetObject("application_renewal-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_renewal_view {
            get {
                object obj = ResourceManager.GetObject("application_renewal-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_requirements {
            get {
                object obj = ResourceManager.GetObject("application-requirements", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_retire {
            get {
                object obj = ResourceManager.GetObject("application-retire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_retirement {
            get {
                object obj = ResourceManager.GetObject("application_retirement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_view {
            get {
                object obj = ResourceManager.GetObject("application-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Arnew {
            get {
                object obj = ResourceManager.GetObject("Arnew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap assessment {
            get {
                object obj = ResourceManager.GetObject("assessment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background_bps {
            get {
                object obj = ResourceManager.GetObject("Background_bps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background_bta2 {
            get {
                object obj = ResourceManager.GetObject("Background_bta2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barangay_list {
            get {
                object obj = ResourceManager.GetObject("barangay_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bill {
            get {
                object obj = ResourceManager.GetObject("bill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BillState {
            get {
                object obj = ResourceManager.GetObject("BillState", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap birthday {
            get {
                object obj = ResourceManager.GetObject("birthday", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bns_rec {
            get {
                object obj = ResourceManager.GetObject("bns_rec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bpls_BPS {
            get {
                object obj = ResourceManager.GetObject("bpls-BPS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BPLS_copy {
            get {
                object obj = ResourceManager.GetObject("BPLS copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bpls_text_trans {
            get {
                object obj = ResourceManager.GetObject("bpls-text-trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bps_nav_addbusrec {
            get {
                object obj = ResourceManager.GetObject("bps-nav_addbusrec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bps_nav_applybusiness {
            get {
                object obj = ResourceManager.GetObject("bps-nav_applybusiness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bps_nav_exit {
            get {
                object obj = ResourceManager.GetObject("bps-nav_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bps_nav_logout {
            get {
                object obj = ResourceManager.GetObject("bps-nav_logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bps_nav_renewbusiness {
            get {
                object obj = ResourceManager.GetObject("bps-nav_renewbusiness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BSP {
            get {
                object obj = ResourceManager.GetObject("BSP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_add {
            get {
                object obj = ResourceManager.GetObject("business-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_delete {
            get {
                object obj = ResourceManager.GetObject("business-delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_edit {
            get {
                object obj = ResourceManager.GetObject("business-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_list {
            get {
                object obj = ResourceManager.GetObject("business-list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Business_permit {
            get {
                object obj = ResourceManager.GetObject("Business-permit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_permit_signatory {
            get {
                object obj = ResourceManager.GetObject("business_permit_signatory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_permita_ace {
            get {
                object obj = ResourceManager.GetObject("business-permita-ace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Business_Record {
            get {
                object obj = ResourceManager.GetObject("Business Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_record_add {
            get {
                object obj = ResourceManager.GetObject("business_record-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_record_delete {
            get {
                object obj = ResourceManager.GetObject("business_record-delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_record_edit {
            get {
                object obj = ResourceManager.GetObject("business_record-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_record_view {
            get {
                object obj = ResourceManager.GetObject("business_record-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_roll {
            get {
                object obj = ResourceManager.GetObject("business-roll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_specialpermit {
            get {
                object obj = ResourceManager.GetObject("business_specialpermit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_view {
            get {
                object obj = ResourceManager.GetObject("business-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_application {
            get {
                object obj = ResourceManager.GetObject("cancel-application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cdo {
            get {
                object obj = ResourceManager.GetObject("cdo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap certificate {
            get {
                object obj = ResourceManager.GetObject("certificate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap certificate_retirement {
            get {
                object obj = ResourceManager.GetObject("certificate-retirement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap certificateretirement {
            get {
                object obj = ResourceManager.GetObject("certificateretirement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap certificatespecial {
            get {
                object obj = ResourceManager.GetObject("certificatespecial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checklist {
            get {
                object obj = ResourceManager.GetObject("checklist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_build_up_tools {
            get {
                object obj = ResourceManager.GetObject("data-build-up-tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_query {
            get {
                object obj = ResourceManager.GetObject("data-query", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Defecient_Business {
            get {
                object obj = ResourceManager.GetObject("Defecient-Business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deficient_businesses {
            get {
                object obj = ResourceManager.GetObject("deficient-businesses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_owner {
            get {
                object obj = ResourceManager.GetObject("delete-owner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap detailed_use {
            get {
                object obj = ResourceManager.GetObject("detailed-use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DILG {
            get {
                object obj = ResourceManager.GetObject("DILG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dilg_report {
            get {
                object obj = ResourceManager.GetObject("dilg-report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap discovery_delinquent {
            get {
                object obj = ResourceManager.GetObject("discovery-delinquent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap discovery_delinquent1 {
            get {
                object obj = ResourceManager.GetObject("discovery-delinquent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap due_date_setup {
            get {
                object obj = ResourceManager.GetObject("due_date_setup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_owner_info {
            get {
                object obj = ResourceManager.GetObject("edit-owner-info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exempted_buss {
            get {
                object obj = ResourceManager.GetObject("exempted_buss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap health_certificate {
            get {
                object obj = ResourceManager.GetObject("health-certificate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hold_records {
            get {
                object obj = ResourceManager.GetObject("hold-records", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inspection_certifiation {
            get {
                object obj = ResourceManager.GetObject("inspection-certifiation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inspector {
            get {
                object obj = ResourceManager.GetObject("Inspector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inspector_module {
            get {
                object obj = ResourceManager.GetObject("inspector-module", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_business {
            get {
                object obj = ResourceManager.GetObject("list-business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap List_Employee_Gender {
            get {
                object obj = ResourceManager.GetObject("List-Employee-Gender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_lessor {
            get {
                object obj = ResourceManager.GetObject("list-lessor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_retirement {
            get {
                object obj = ResourceManager.GetObject("list-retirement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ListBusinesses_not_mapped {
            get {
                object obj = ResourceManager.GetObject("ListBusinesses_not-mapped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maplist_woutpermit {
            get {
                object obj = ResourceManager.GetObject("maplist-woutpermit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maplist_wpermit {
            get {
                object obj = ResourceManager.GetObject("maplist-wpermit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mappedbusiness_onqueue {
            get {
                object obj = ResourceManager.GetObject("mappedbusiness-onqueue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap module_rights {
            get {
                object obj = ResourceManager.GetObject("module_rights", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notice_delinquency {
            get {
                object obj = ResourceManager.GetObject("notice-delinquency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap noticessaved_woutpermit {
            get {
                object obj = ResourceManager.GetObject("noticessaved-woutpermit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap noticessaved_wpermit {
            get {
                object obj = ResourceManager.GetObject("noticessaved-wpermit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OnQueue_Business {
            get {
                object obj = ResourceManager.GetObject("OnQueue-Business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap owership_record {
            get {
                object obj = ResourceManager.GetObject("owership-record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap owner_query {
            get {
                object obj = ResourceManager.GetObject("owner-query", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PaperTrail {
            get {
                object obj = ResourceManager.GetObject("PaperTrail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap permit_update {
            get {
                object obj = ResourceManager.GetObject("permit_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap permit_update_application {
            get {
                object obj = ResourceManager.GetObject("permit-update-application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap permits_certificate {
            get {
                object obj = ResourceManager.GetObject("permits-certificate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Record_Update {
            get {
                object obj = ResourceManager.GetObject("Record-Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Record_Update_Cancel {
            get {
                object obj = ResourceManager.GetObject("Record-Update-Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ren {
            get {
                object obj = ResourceManager.GetObject("ren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap renewal_application_add {
            get {
                object obj = ResourceManager.GetObject("renewal-application-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap renewal_application_edit {
            get {
                object obj = ResourceManager.GetObject("renewal-application-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap renewal_application_view {
            get {
                object obj = ResourceManager.GetObject("renewal-application-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap replace_bin_owner {
            get {
                object obj = ResourceManager.GetObject("replace-bin-owner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap replace_owner_accounts {
            get {
                object obj = ResourceManager.GetObject("replace-owner-accounts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_files {
            get {
                object obj = ResourceManager.GetObject("report-files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_files1 {
            get {
                object obj = ResourceManager.GetObject("report-files1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_manager {
            get {
                object obj = ResourceManager.GetObject("report-manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_manager1 {
            get {
                object obj = ResourceManager.GetObject("report-manager1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportlist_gender {
            get {
                object obj = ResourceManager.GetObject("reportlist-gender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retirement_ace {
            get {
                object obj = ResourceManager.GetObject("retirement-ace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retirement_report {
            get {
                object obj = ResourceManager.GetObject("retirement-report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sanitary_permit {
            get {
                object obj = ResourceManager.GetObject("sanitary-permit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scheds_other_chrgs {
            get {
                object obj = ResourceManager.GetObject("scheds_other_chrgs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scheds_tax_fees {
            get {
                object obj = ResourceManager.GetObject("scheds_tax_fees", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set_dfault {
            get {
                object obj = ResourceManager.GetObject("set_dfault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap special_application_add {
            get {
                object obj = ResourceManager.GetObject("special-application-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap special_application_edit {
            get {
                object obj = ResourceManager.GetObject("special-application-edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap special_application_view {
            get {
                object obj = ResourceManager.GetObject("special-application-view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Special_Ordinance {
            get {
                object obj = ResourceManager.GetObject("Special-Ordinance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Special_Ordinance1 {
            get {
                object obj = ResourceManager.GetObject("Special-Ordinance1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap special_permit {
            get {
                object obj = ResourceManager.GetObject("special-permit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap summary_business {
            get {
                object obj = ResourceManager.GetObject("summary-business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summary_business_by_Section {
            get {
                object obj = ResourceManager.GetObject("Summary_business-by-Section", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap summarybusiness_records {
            get {
                object obj = ResourceManager.GetObject("summarybusiness-records", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap summarybusiness_yearreg {
            get {
                object obj = ResourceManager.GetObject("summarybusiness-yearreg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap summaryreport_brgy_sec {
            get {
                object obj = ResourceManager.GetObject("summaryreport_brgy-sec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_config_2 {
            get {
                object obj = ResourceManager.GetObject("system-config-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap task_manager {
            get {
                object obj = ResourceManager.GetObject("task-manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unofficial_Business {
            get {
                object obj = ResourceManager.GetObject("Unofficial-Business", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unofficial_businesses {
            get {
                object obj = ResourceManager.GetObject("unofficial-businesses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unrenewed {
            get {
                object obj = ResourceManager.GetObject("unrenewed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_setup {
            get {
                object obj = ResourceManager.GetObject("user-setup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Violation_table {
            get {
                object obj = ResourceManager.GetObject("Violation-table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap violation_table_ace {
            get {
                object obj = ResourceManager.GetObject("violation_table_ace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap waive_surcharge_penalty {
            get {
                object obj = ResourceManager.GetObject("waive-surcharge-penalty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap working_permit {
            get {
                object obj = ResourceManager.GetObject("working-permit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoning_certifiation {
            get {
                object obj = ResourceManager.GetObject("zoning-certifiation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
